const guestsType = {
    REGULAR: "REGULAR",
    GROOMSMAN: "GROOMSMAN",
    MAID: "MAID",
    GROOMSMOTHER: "GROOMSMOTHER",
    GROOMSFATHER: "GROOMSFATHER",
    BRIDESMOTHER: "BRIDESMOTHER",
    BRIDESFATHER: "BRIDESFATHER"
}

module.exports.guestsTypeEnum = guestsType